### ISSUE TITLE
Footer content overflows. 

### ISSUE THREAD

**Issue by vshivam** [privly/privly-android#40]
The content in the footer of Privly Applications overflows on mobile screens. 

Here's a screenshot. 

![screenshot from 2015-03-04 14 06 52](https://cloud.githubusercontent.com/assets/831071/6478955/ff9b6c5a-c277-11e4-8665-29f1b69fbd4b.png)

These are the templates that need to be edited : 
* https://github.com/privly/privly-applications/blob/master/templates/show.html.template#L150
* https://github.com/privly/privly-applications/blob/master/templates/new.html.template#L135

And here's how you can build PrivlyApplications : https://priv.ly/pages/develop.html#BuildSystem

**Comment by smcgregor** [comment]
The footer that starts with "Donate" and ends with "DMCA"?

**Comment by vshivam** [comment]
Yep.

**Comment by arjunvijayvargiya** [comment]
I updated PrivlyApplicationFragment.java inorder to fit the webpage withe screen of the mobile. Pull request #48 .I have changed LoginActivity.java as It was not recognizing at all.And this issue is resolved by adding  "webview.getSettings().setLayoutAlgorithm(WebSettings.LayoutAlgorithm.SINGLE_COLUMN);"
to privlyApllicationFragment.java 
![screenshot_2015-03-07-16-14-24](https://cloud.githubusercontent.com/assets/7685777/6541154/6965213c-c4e7-11e4-9972-cd68c2b2e33e.png)

**Comment by gitanshu** [comment]
While it was a smart move to use SINGLE_COLUMN layout, the issue also affects the privly mobile site (as you can see in the screenshot by vshivam) and thus, this issue be better fixed in privlyapplications than for just android. The required links are available in the first post by vshivam.

**Comment by vshivam** [comment]
This is not just an issue with the android version. It's an issue with Privly Applications in general (which is used by the android version) and  needs to be fixed there.

**Comment by arjunvijayvargiya** [comment]
While going through the privly application code, I figured out that this problem can be fixed by changing the value of height field to -1% or -1 px instead of using 60 px in the height field of #footer. I did this change in the following file and particular line as can be seen here

https://github.com/privly/privly-applications/blob/master/shared/css/top/top.css#L29

Although I am not sure whether its correct or not , when I ran the app on my mobile it worked the footer content is not overflowing any more.
![footercontent](https://cloud.githubusercontent.com/assets/7685777/6578833/6fcd88c0-c76c-11e4-88cb-d7a628fd1a03.png).

**Comment by vshivam** [comment]
I'm not sure if this is the best way to handle this issue. But I think what might work is to set a min-height property for the footer rather than a fixed height. 

@smcgregor will be help you out better with this.

**Comment by arjunvijayvargiya** [comment]
I will try doing with min-height and will let you know.

**Comment by arjunvijayvargiya** [comment]
I have updated height to min-height in top.css by putting the value 60 px as it was before, it worked.
reference:https://github.com/privly/privly-applications/blob/master/shared/css/top/top.css#L29.I am just adding screenshots to show the differences between the three edits
Height-60px
![height-60px](https://cloud.githubusercontent.com/assets/7685777/6591978/998990f6-c7ed-11e4-9d5f-9755aac2719f.PNG)  
Height -1px
![height-1](https://cloud.githubusercontent.com/assets/7685777/6591980/a8c6dfd8-c7ed-11e4-9af1-c8d1f8eeec51.PNG) 
min-height 60px
![minheight](https://cloud.githubusercontent.com/assets/7685777/6591996/ba4a062c-c7ed-11e4-9520-b3f217ceaef8.PNG)

**Comment by vshivam** [comment]
The screenshots are too small. Can't really make out the difference.

**Comment by arjunvijayvargiya** [comment]
height: 60px; (current)(overflow)
![height0](https://cloud.githubusercontent.com/assets/7685777/6593959/05de493a-c803-11e4-89fa-25e9a59bc432.PNG)
height:-1px;(no overflow)
![height1](https://cloud.githubusercontent.com/assets/7685777/6593982/24a911ba-c803-11e4-840f-b11e09992c1a.PNG)
min-height:60px;(no overflow)
![height2](https://cloud.githubusercontent.com/assets/7685777/6593993/370772e8-c803-11e4-8257-193a68184400.PNG)

**Comment by smcgregor** [comment]
I think this looks good. Time for a pull request on privly-applications?

**Comment by arjunvijayvargiya** [comment]
thanks @smcgregor .I will make a pull request on privly application.

**Comment by arjunvijayvargiya** [comment]
I made a pull request#213 
reference: https://github.com/privly/privly-applications/pull/213
