### ISSUE TITLE
Error in building Android

### ISSUE THREAD

**Issue by mkash32** [privly/privly-android#63]
Some issues came when trying to run the app:

1) https://gist.github.com/mkash32/7ecb48cdf5881abdbbfe :- After searching, I found the fix for this would be to change compile sdk in the build.gradle file to "23",build tootls to "23.0.0", and changing to appcompat-v7:23.0.+. After applying this fix the build was fine, but there another issue arose (during compile I assume)

2) https://gist.github.com/mkash32/fe8b9f87bc561311dad2 :- Researching about this issue led to excluding some http libraries because duplicates will be compiled when we include the android play services in the dependencies in build.gradle (app module). Applying this fix led to another issue.

3)https://gist.github.com/mkash32/9d63765c8c3ce90c3d1f :- The fix for this seemed very complex and unnecessary.

**Comment by gitanshu** [comment]
From the top of my head: 

1)

2). The Apache HTTP library is no longer available in API 23. The makeshift fix for that would be to add `useLibrary 'org.apache.http.legacy'` in build.gradle of app. In longer run, apache http library dependency should be removed from app and replaced with HTTPUrlConnection based implementation.

3). This occurs because the app has hit method limit for dex file. 1 dex file can have 65536 methods. The simple way to solve this is to set `multiDexEnabled true` in defaultConfig in app's build.gradle. However, the root cause of the problem is inclusion of the monolithic play services library. We should identify required play services APIs and selectively add them. Read section `Selectively compiling APIs into your executable` on [this webpage](https://developers.google.com/android/guides/setup)

**Comment by mkash32** [comment]
I implemented the changes you suggested, I also had to change compile 'com.google.android.gms:play-services:+' to compile 'com.google.android.gms:play-services:8.4.0' to get it working.
Is this configuration dependent on the compuleSDK, build version, or android studio? (Would this configuration be applicable for anyone developing on the app?)

**Comment by vshivam** [comment]
The code hasn't been updated to target android-23 yet. Hence the build issues. 

I'd suggest using the HTTPUrlConnection class instead of using the legacy dependency.

**Comment by mkash32** [comment]
I was thinking of using OkHttp library to make an asynchronous http request, eliminating the need of AsyncTask and also resulting in better performance. What is your opinion about using OkHttp?

**Comment by vshivam** [comment]
OkHttp is generally considered better than AsyncTask but we don't use it because we never needed it. I don't see why we should change now.

**Comment by vshivam** [comment]
@mkash32 Could you try building the project from the develop branch. The develop branch targets 23.

**Comment by mkash32** [comment]
I tried it out, the develop branch is working fine.
