### ISSUE TITLE
ShowContentFragment's Webview doesn't scroll. 

### ISSUE THREAD

**Issue by vshivam** [privly/privly-android#66]
Self Explanatory. 

To reproduce, generate a Privly Url for a longer text and view the Url within the application.

**Comment by smcgregor** [comment]
Is this a privly-android problem or a privly-applications problem?

**Comment by vshivam** [comment]
This is specific to privly-android.

**Comment by mkash32** [comment]
The touch event is being intercepted by the gesture listener so scrolling isn't taking place.
I commented out the [listener](http://github.com/privly/privly-android/tree/master/app/src/main/java/ly/priv/mobile/gui/fragments/ShowContentFragment.java#L101) and the scrolling is working properly. 

Since the webview requires horizontal and vertical scrolling, I think using a gesture listener would be a little difficult to manage.

@vshivam Would including buttons for previous/next post be a good approach? Since we just need it for the android device we can just have the buttons hover above the web view.

**Comment by vshivam** [comment]
If we handle the return values from the gesture listener properly, the scrolling should work.

I think we also need to provide visual clues to the user in case of multiple Privly Urls.

**Comment by mkash32** [comment]
So small/slow touch events (where the X distance is relatively less) should be treated as scroll and large/fast touch events (where X distance is large,fling) should be treated as a change in the content?

**Comment by mkash32** [comment]
In what situation would multiple Privly Urls be present?

**Comment by mkash32** [comment]
![screenshot_20160220-224619](https://cloud.githubusercontent.com/assets/11131759/13198037/12fb5aea-d824-11e5-8d43-07b6dfa0346b.png)
This is my idea for providing visual clues. How does it look?

**Comment by vshivam** [comment]
@mkash32 

* All you need to do to enable scrolling is to pass on the the touch event to the webview whenever the `onFling` method returns false. You'll need to update the return values in the `onFling` method though. Whenever we consume a swipe we'll need to return true and false otherwise. It's possible that we might not need to override the `onScroll` method at all. 

* When we view some content from an external source inside our application, Twitter for instance, it's possible that a tweet has two Privly URLs. If you tap on that tweet, the fragment allows you to swipe and view content from both the URLs. 

* The idea of page indicator looks good. Could you explain a bit as to why you're wrapping the whole thing in a CardView ? I haven't had a chance to work with them. 

* You might wanna try out a different type of indicator. Rather than adding an exact number of drawables, it's probably better to have something that tells the user that there's still more content to swipe to. While this might be a little far fetched, the current solution will look a little odd in case of say 15 Privly URLs.

**Comment by mkash32** [comment]
![screenshot_20160222-165103](https://cloud.githubusercontent.com/assets/11131759/13216888/b96060cc-d984-11e5-921a-18b1a4957424.png)

Is this better?

**Comment by mkash32** [comment]
@vshivam 
For the scrolling issue, passing on the touch event requires a motion event. In the `onFling` method we have two motion events as parameters (e1 and e2), which one would we pass? I think we would require all the motion events from e1 to e2 for proper scrolling to take place. 
And I feel we would need to override `onScroll` because the listener is automatically intercepting the events, without overriding it the scroll events wouldn't go to the webview automatically.
I used the webview's `flingScroll` and `scrollBy` methods to obtain successful scrolling, was there any downside to this implementation?

I just used the card view for the elevation aspect. I removed the card view wrapping and just included `android:elevation` now. I faced some issues with the elevation attribute in the past (some older android versions wouldn't display the elevation), but the attribute seems to be working fine (I probably made a mistake when I used it earlier).

**Comment by vshivam** [comment]
If you return the MotionEvent object received in the onTouchListener, back to the WebView depending on the return value of `mGestureDetector.onTouchEvent(event)`, the scrolling should work. It's because the touch events are now being passed on to the WebView whenever a swipe is not detected. We'll also not need to override the `onDown()` method in the SwipeGestureDetector. 

If this approach works, the good thing is that it'll make sure that the WebView still retains it's (most/all?) other default behaviors. You'll be able to enable zoom controls on the WebView if need be. Handling just the scroll will only tackle that specific problem. 

I also believe that the lesser the number of methods you need to override, the better the solution. You can't always predict what the side-effect/s might be, as evident from this issue. 

The page indicator looks good. I guess we could keep the color of the indicator bar same as the rest of the page just to keep things uniform. The next/previous icon can be a little bigger. We use the android-iconify library for displaying icons. Check it out for any relevant icons you might need.

**Comment by mkash32** [comment]
Ok, cool. Yeah passing the touch event directly to the webview sounds much better than manually scrolling on various events.

Why is it necessary for `onDown()` method to return true for proper swiping to take place? I tried removing the method and the swiping was working fine.

**Comment by vshivam** [comment]
That's what I said in my last comment.  We don't need to override it. You can get rid of the whole thing.

**Comment by mkash32** [comment]
Oh sorry about that, I misread that part.

**Comment by vshivam** [comment]
Made some changes to your PR and merged. Check it out here : https://github.com/privly/privly-android/commit/5bc95851b14f9f78809ef0ee8f53d1a6da7316cc
